### ISSUE TITLE
ModuleNotFoundError: No module named 'langchain_google_vertexai'

### ISSUE THREAD

**Issue by bobwatcherx** [tvaroska/fletchain#1]
how to fix error . i install you pip pacckage but error when runnning
```

Traceback (most recent call last):
  File "C:\Users\LENOVO\Pictures\fletapp\fletlottie\main.py", line 10, in <module>
    from langchain_google_vertexai import ChatVertexAI
ModuleNotFoundError: No module named 'langchain_google_vertexai'
```

**Comment by Baxx95** [comment]
run "!pip install langchain_google_vertexai" it work for me

**Comment by tvaroska** [comment]
Demo does require vertex ai models. Package itself does not.

**Comment by bobwatcherx** [comment]
i still error

```
C:\Users\LENOVO\Pictures\mainan\webdood\phub>
C:\Users\LENOVO\Pictures\mainan\webdood\phub>flet main.py
Traceback (most recent call last):
  File "C:\Users\LENOVO\Pictures\mainan\webdood\phub\main.py", line 10, in <module>
    from langchain_google_vertexai import ChatVertexAI
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain_google_vertexai\__init__.py", line 14, in <module>
    from langchain_google_vertexai.chains import create_structured_runnable
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain_google_vertexai\chains.py", line 19, in <module>
    from langchain_google_vertexai.functions_utils import PydanticFunctionsOutputParser
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain_google_vertexai\functions_utils.py", line 26, in <module>
    from langchain_core.utils.function_calling import (
ImportError: cannot import name 'convert_to_openai_tool' from 'langchain_core.utils.function_calling' (C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain_core\utils\function_calling.py)
```

```
C:\Users\LENOVO\Pictures\mainan\webdood\phub>flet --version
0.24.1
```

**Comment by tvaroska** [comment]
Do you use one of the examples there or can you post your code if not? thx

**Comment by joesandiroz2** [comment]
> Do you use one of the examples there or can you post your code if not? thx

This is my second account above. So I am still using your sample code from your github.

**Comment by joesandiroz2** [comment]
Can you run it with the flet version I gave above? And with what version of python did you succeed? Maybe that's the cause.

**Comment by tvaroska** [comment]
So it works for me

flet - 0.24.1
python 3.9, 3.10

bit of a challenge with langchain versioning - will have to change langchain >= 0.3.0 

Can you post version of vertexai library? The error is strange because demo examples does not use tools nor pydantic output parser.
